name: Autotag

on: [push]
#on:
#  push:
#    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Tag new version
        uses: phish108/autotag-action@v1.1.55
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          bump: minor
          with-v: true
          dry-run: true # remove when ready
