name: Autotag

on: [push]
#on:
#  push:
#    branches: main

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Tag new version
        uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
          bump: minor
          with-v: true
          release-branch: main,autotag # remove autotag when ready
          dry-run: true # remove when ready
